<?php
// Config file

$config = array(
	'Dictionary' => array(
		'name' => 'Raison sociale',
		'website' => 'Site web',
		'zip_code' => 'Code postal',
		'street_name' => 'Rue/Bd/Av',
		'city_name' => 'Ville',
		'contact' => 'Contact principal',
		'activity' => 'Activité',
		'siren' => 'Siren',
		'legal_status' => 'Statut légal',
		'other_status' => 'Autre statut',
		'social_capital' => 'Capital social',
		'creation_date' => 'Date de création',
		'total_shares' => 'Nombre de parts totales',
		'status' => 'Statut',
		'is_bs_closed' => 'Existe-t-il un bilan pour la société ?',
		'closing_date' => 'Date de clôture',
		'is_positive' => 'Le bilan était (ou sera t-il) positif (> ou = 0) ou négatif ?',
		'civility' => 'Civilité',
		'first_name' => 'Prénom',
		'last_name' => 'Nom',
		'pro_email' => 'Email professionnel',
		'perso_email' => 'Email personnel',
		'phone' => 'Téléphone',
		'social_situation' => 'Situation sociale',
		'other_situation' => 'Autre situation',
		'birthdate' => 'Date de naissance',
		'birth_city' => 'Ville de naissance',
		'birth_country' => 'Pays de naissance',
		'shares' => 'Nombre de parts',
		'loan_amount' => 'Montant du prêt',
		'eligibility' => 'Eligibilité',
		'loan_affectation' => 'Affectation du prêt',
		'is_payed' => 'Est-ce payé',
		'had_company' => 'Avez vous déjà créé une Société en France (y compris Auto Entrepreneur) ?',
		'is_european' => 'Êtes-vous ressortissant Européen ?',
		'is_hosted' => 'Êtes-vous hébergé par un tiers ?',
		'kbis' => 'KBIS de la société',
		'company_rib' => 'RIB de la société',
		'work_certificate' => 'Certificat de travail',
		'id_card' => 'Pièce d\'identité',
		'applicant_rib' => 'RIB du demandeur',
		'proof_home' => 'Justificatif de domicile',
		'accommodation_certificate' => 'Attestation d\'hébergement',
		'accommodating_id_card' => 'Pièce d\'identité de l\'hébergeant',
		'LO' => 'Connexion',
		'SI' => 'Inscription',
		'NL' => 'Nouveau token',
		'Company' => 'Société',
		'Profile' => 'Demandeur',
		'uncomplete' => 'incomplet',
		'valid' => 'validé',
		'waiting' => 'en attente de validation',
		'complete' => ' Dossier complet'),
	'ItemPerPage' => 10
);
?>